In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/workflow_tasks.csv")

In [3]:
df.head()

,ticket_id,created_at,resolved_at,priority,category,assigned_group
0,1,2023-03-18 00:00:00,2023-03-18 22:29:00,Low,Network,Support_Team_B
1,2,2023-06-02 09:00:00,2023-06-02 20:03:48,Medium,Software,DB_Admin
2,3,2023-03-01 08:00:00,2023-03-01 10:32:03,Critical,Software,Support_Team_A
3,4,2023-03-05 23:00:00,2023-03-06 03:20:48,Medium,Hardware,DB_Admin
4,5,2023-01-19 02:00:00,2023-01-19 15:15:25,Medium,Database,Security

In [4]:
df.shape

(3000, 6)

In [5]:
df.columns.tolist()

['ticket_id',
 'created_at',
 'resolved_at',
 'priority',
 'category',
 'assigned_group']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ticket_id       3000 non-null   int64
 1   created_at      3000 non-null   str
 2   resolved_at     3000 non-null   str
 3   priority        3000 non-null   str
 4   category        3000 non-null   str
 5   assigned_group  3000 non-null   str
dtypes: int64(1), str(5)
memory usage: 140.8 KB

In [7]:
df.isnull().sum()

ticket_id         0
created_at        0
resolved_at       0
priority          0
category          0
assigned_group    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["priority"].unique()

<StringArray>
['Low', 'Medium', 'Critical', 'High']
Length: 4, dtype: str

In [10]:
df["status"].unique()

KeyError: 'status'

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ticket_id       3000 non-null   int64
 1   created_at      3000 non-null   str
 2   resolved_at     3000 non-null   str
 3   priority        3000 non-null   str
 4   category        3000 non-null   str
 5   assigned_group  3000 non-null   str
dtypes: int64(1), str(5)
memory usage: 140.8 KB

In [12]:
import pandas as pd
df = pd.read_csv("../data/raw/workflow_tasks.csv")
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000047,Closed,False,1,0,8,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00
2,INC0000057,Closed,False,0,0,6,True,Caller 4416,Opened by 8,29/2/2016 06:10,...,False,Do Not Notify,Problem ID 2,?,?,?,code 10,Resolved by 5,1/3/2016 2:55,6/3/2016 3:00
3,INC0000060,Closed,False,0,0,3,True,Caller 4491,Opened by 180,29/2/2016 06:38,...,False,Do Not Notify,?,?,?,?,code 3,Resolved by 113,2/3/2016 12:06,7/3/2016 13:00
4,INC0000062,Closed,False,1,0,7,False,Caller 3765,Opened by 180,29/2/2016 06:58,...,False,Do Not Notify,?,?,?,?,code 7,Resolved by 62,29/2/2016 15:51,5/3/2016 16:00

In [13]:
cd ~/MSc_Project/workflow_predictive_analytics
cp data/raw/workflow_tasks.csv data/raw/workflow_tasks_backup.csv
cp ~/Downloads/incident_event_log_reduced.csv data/raw/workflow_tasks.csv
ls data/raw

SyntaxError: invalid syntax (2547614711.py, line 1)

In [14]:
df = pd.read_csv("../data/raw/workflow_tasks.csv")
df.head()
df.columns.tolist()
df.shape

(24918, 36)

In [15]:
df.shape

(24918, 36)

In [16]:
df.columns.tolist()

['number',
 'incident_state',
 'active',
 'reassignment_count',
 'reopen_count',
 'sys_mod_count',
 'made_sla',
 'caller_id',
 'opened_by',
 'opened_at',
 'sys_created_by',
 'sys_created_at',
 'sys_updated_by',
 'sys_updated_at',
 'contact_type',
 'location',
 'category',
 'subcategory',
 'u_symptom',
 'cmdb_ci',
 'impact',
 'urgency',
 'priority',
 'assignment_group',
 'assigned_to',
 'knowledge',
 'u_priority_confirmation',
 'notify',
 'problem_id',
 'rfc',
 'vendor',
 'caused_by',
 'closed_code',
 'resolved_by',
 'resolved_at',
 'closed_at']

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24918 entries, 0 to 24917
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   number                   24918 non-null  str
 1   incident_state           24918 non-null  str
 2   active                   24918 non-null  bool
 3   reassignment_count       24918 non-null  int64
 4   reopen_count             24918 non-null  int64
 5   sys_mod_count            24918 non-null  int64
 6   made_sla                 24918 non-null  bool
 7   caller_id                24918 non-null  str
 8   opened_by                24918 non-null  str
 9   opened_at                24918 non-null  str
 10  sys_created_by           24918 non-null  str
 11  sys_created_at           24918 non-null  str
 12  sys_updated_by           24918 non-null  str
 13  sys_updated_at           24918 non-null  str
 14  contact_type             24918 non-null  str
 15  location                 24918 non-null  str
 16  category                 24918 non-null  str
 17  subcategory              24918 non-null  str
 18  u_symptom                24918 non-null  str
 19  cmdb_ci                  24918 non-null  str
 20  impact                   24918 non-null  str
 21  urgency                  24918 non-null  str
 22  priority                 24918 non-null  str
 23  assignment_group         24918 non-null  str
 24  assigned_to              24918 non-null  str
 25  knowledge                24918 non-null  bool
 26  u_priority_confirmation  24918 non-null  bool
 27  notify                   24918 non-null  str
 28  problem_id               24918 non-null  str
 29  rfc                      24918 non-null  str
 30  vendor                   24918 non-null  str
 31  caused_by                24918 non-null  str
 32  closed_code              24918 non-null  str
 33  resolved_by              24918 non-null  str
 34  resolved_at              24918 non-null  str
 35  closed_at                24918 non-null  str
dtypes: bool(4), int64(3), str(29)
memory usage: 6.2 MB

In [18]:
import pandas as pd

df = pd.read_csv("../data/raw/workflow_tasks.csv")
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000047,Closed,False,1,0,8,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00
2,INC0000057,Closed,False,0,0,6,True,Caller 4416,Opened by 8,29/2/2016 06:10,...,False,Do Not Notify,Problem ID 2,?,?,?,code 10,Resolved by 5,1/3/2016 2:55,6/3/2016 3:00
3,INC0000060,Closed,False,0,0,3,True,Caller 4491,Opened by 180,29/2/2016 06:38,...,False,Do Not Notify,?,?,?,?,code 3,Resolved by 113,2/3/2016 12:06,7/3/2016 13:00
4,INC0000062,Closed,False,1,0,7,False,Caller 3765,Opened by 180,29/2/2016 06:58,...,False,Do Not Notify,?,?,?,?,code 7,Resolved by 62,29/2/2016 15:51,5/3/2016 16:00

In [19]:
df.columns.tolist()

['number',
 'incident_state',
 'active',
 'reassignment_count',
 'reopen_count',
 'sys_mod_count',
 'made_sla',
 'caller_id',
 'opened_by',
 'opened_at',
 'sys_created_by',
 'sys_created_at',
 'sys_updated_by',
 'sys_updated_at',
 'contact_type',
 'location',
 'category',
 'subcategory',
 'u_symptom',
 'cmdb_ci',
 'impact',
 'urgency',
 'priority',
 'assignment_group',
 'assigned_to',
 'knowledge',
 'u_priority_confirmation',
 'notify',
 'problem_id',
 'rfc',
 'vendor',
 'caused_by',
 'closed_code',
 'resolved_by',
 'resolved_at',
 'closed_at']

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24918 entries, 0 to 24917
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   number                   24918 non-null  str
 1   incident_state           24918 non-null  str
 2   active                   24918 non-null  bool
 3   reassignment_count       24918 non-null  int64
 4   reopen_count             24918 non-null  int64
 5   sys_mod_count            24918 non-null  int64
 6   made_sla                 24918 non-null  bool
 7   caller_id                24918 non-null  str
 8   opened_by                24918 non-null  str
 9   opened_at                24918 non-null  str
 10  sys_created_by           24918 non-null  str
 11  sys_created_at           24918 non-null  str
 12  sys_updated_by           24918 non-null  str
 13  sys_updated_at           24918 non-null  str
 14  contact_type             24918 non-null  str
 15  location                 24918 non-null  str
 16  category                 24918 non-null  str
 17  subcategory              24918 non-null  str
 18  u_symptom                24918 non-null  str
 19  cmdb_ci                  24918 non-null  str
 20  impact                   24918 non-null  str
 21  urgency                  24918 non-null  str
 22  priority                 24918 non-null  str
 23  assignment_group         24918 non-null  str
 24  assigned_to              24918 non-null  str
 25  knowledge                24918 non-null  bool
 26  u_priority_confirmation  24918 non-null  bool
 27  notify                   24918 non-null  str
 28  problem_id               24918 non-null  str
 29  rfc                      24918 non-null  str
 30  vendor                   24918 non-null  str
 31  caused_by                24918 non-null  str
 32  closed_code              24918 non-null  str
 33  resolved_by              24918 non-null  str
 34  resolved_at              24918 non-null  str
 35  closed_at                24918 non-null  str
dtypes: bool(4), int64(3), str(29)
memory usage: 6.2 MB

In [21]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000047,Closed,False,1,0,8,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00
2,INC0000057,Closed,False,0,0,6,True,Caller 4416,Opened by 8,29/2/2016 06:10,...,False,Do Not Notify,Problem ID 2,?,?,?,code 10,Resolved by 5,1/3/2016 2:55,6/3/2016 3:00
3,INC0000060,Closed,False,0,0,3,True,Caller 4491,Opened by 180,29/2/2016 06:38,...,False,Do Not Notify,?,?,?,?,code 3,Resolved by 113,2/3/2016 12:06,7/3/2016 13:00
4,INC0000062,Closed,False,1,0,7,False,Caller 3765,Opened by 180,29/2/2016 06:58,...,False,Do Not Notify,?,?,?,?,code 7,Resolved by 62,29/2/2016 15:51,5/3/2016 16:00

In [22]:
df.isnull().sum()

number                     0
incident_state             0
active                     0
reassignment_count         0
reopen_count               0
sys_mod_count              0
made_sla                   0
caller_id                  0
opened_by                  0
opened_at                  0
sys_created_by             0
sys_created_at             0
sys_updated_by             0
sys_updated_at             0
contact_type               0
location                   0
category                   0
subcategory                0
u_symptom                  0
cmdb_ci                    0
impact                     0
urgency                    0
priority                   0
assignment_group           0
assigned_to                0
knowledge                  0
u_priority_confirmation    0
notify                     0
problem_id                 0
rfc                        0
vendor                     0
caused_by                  0
closed_code                0
resolved_by                0
resolved_at                0
closed_at                  0
dtype: int64

In [23]:
df.head()
df.columns.tolist()
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 24918 entries, 0 to 24917
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   number                   24918 non-null  str
 1   incident_state           24918 non-null  str
 2   active                   24918 non-null  bool
 3   reassignment_count       24918 non-null  int64
 4   reopen_count             24918 non-null  int64
 5   sys_mod_count            24918 non-null  int64
 6   made_sla                 24918 non-null  bool
 7   caller_id                24918 non-null  str
 8   opened_by                24918 non-null  str
 9   opened_at                24918 non-null  str
 10  sys_created_by           24918 non-null  str
 11  sys_created_at           24918 non-null  str
 12  sys_updated_by           24918 non-null  str
 13  sys_updated_at           24918 non-null  str
 14  contact_type             24918 non-null  str
 15  location                 24918 non-null  str
 16  category                 24918 non-null  str
 17  subcategory              24918 non-null  str
 18  u_symptom                24918 non-null  str
 19  cmdb_ci                  24918 non-null  str
 20  impact                   24918 non-null  str
 21  urgency                  24918 non-null  str
 22  priority                 24918 non-null  str
 23  assignment_group         24918 non-null  str
 24  assigned_to              24918 non-null  str
 25  knowledge                24918 non-null  bool
 26  u_priority_confirmation  24918 non-null  bool
 27  notify                   24918 non-null  str
 28  problem_id               24918 non-null  str
 29  rfc                      24918 non-null  str
 30  vendor                   24918 non-null  str
 31  caused_by                24918 non-null  str
 32  closed_code              24918 non-null  str
 33  resolved_by              24918 non-null  str
 34  resolved_at              24918 non-null  str
 35  closed_at                24918 non-null  str
dtypes: bool(4), int64(3), str(29)
memory usage: 6.2 MB

number                     0
incident_state             0
active                     0
reassignment_count         0
reopen_count               0
sys_mod_count              0
made_sla                   0
caller_id                  0
opened_by                  0
opened_at                  0
sys_created_by             0
sys_created_at             0
sys_updated_by             0
sys_updated_at             0
contact_type               0
location                   0
category                   0
subcategory                0
u_symptom                  0
cmdb_ci                    0
impact                     0
urgency                    0
priority                   0
assignment_group           0
assigned_to                0
knowledge                  0
u_priority_confirmation    0
notify                     0
problem_id                 0
rfc                        0
vendor                     0
caused_by                  0
closed_code                0
resolved_by                0
resolved_at                0
closed_at                  0
dtype: int64